import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Minimal-nextjs",
  description: "Generated by Dave",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 min-h-screen`}
      >
        {/* Header */}
        <header className="bg-white shadow-sm border-b">
          <div className="max-w-4xl mx-auto px-4 py-4">
            <nav className="flex items-center space-x-6">
              <Link href="/" className="text-xl font-semibold text-gray-900 hover:text-blue-600 transition-colors">
                Minimal Next.js
              </Link>
              <div className="flex space-x-4">
                <Link href="/" className="text-gray-600 hover:text-blue-600 transition-colors">
                  Home (Static)
                </Link>
                <Link href="/about" className="text-gray-600 hover:text-blue-600 transition-colors">
                  About (Dynamic)
                </Link>

                <Link href="/client" className="text-gray-600 hover:text-blue-600 transition-colors">
                  Client (Auto - Static)
                </Link>

              </div>
            </nav>
          </div>
        </header>

        {/* Main Content */}
        <main className="max-w-4xl mx-auto px-4 py-8">
          {children}
        </main>

        {/* Footer */}
        <footer className="mt-auto bg-white border-t py-6">
          <div className="max-w-4xl mx-auto px-4 text-center text-gray-500 text-sm">
            Built with Next.js and TailwindCSS
          </div>
        </footer>
      </body>
    </html>
  );
}
