import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { readFileSync } from "fs";
import { join } from "path";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Minimal-nextjs",
  description: "Generated by Dave",
};

function getGitInfo() {
  try {
    const gitInfoPath = join(process.cwd(), 'git-info.json');
    const gitInfo = JSON.parse(readFileSync(gitInfoPath, 'utf8'));
    return gitInfo;
  } catch (error) {
    return null;
  }
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const gitInfo = getGitInfo();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 min-h-screen`}
      >
        {/* Header */}
        <header className="bg-white shadow-sm border-b">
          <div className="max-w-4xl mx-auto px-4 py-4">
            <nav className="flex items-center space-x-6">
              <Link href="/" className="text-xl font-semibold text-gray-900 hover:text-blue-600 transition-colors" prefetch={false}>
                Minimal Next.js
              </Link>
              <div className="flex space-x-4">
                <Link href="/" className="text-gray-600 hover:text-blue-600 transition-colors" prefetch={false}>
                  Home Server Component (Static SSG)
                </Link>
                <Link href="/about" className="text-gray-600 hover:text-blue-600 transition-colors" prefetch={false}>
                  About Server Component (Dynamic SSR)
                </Link>

                <Link href="/client" className="text-gray-600 hover:text-blue-600 transition-colors" prefetch={false}>
                  Client Component (Static SSG)
                </Link>
                <Link href="/posts" className="text-gray-600 hover:text-blue-600 transition-colors" prefetch={false}>
                  Posts Server Component (Dynamic SSR)
                </Link>
                <Link href="/contact" className="text-gray-600 hover:text-blue-600 transition-colors" prefetch={false}>Contact Component inside Dynamic Server Component</Link>
                <Link href="/users" className="text-gray-600 hover:text-blue-600 transition-colors" prefetch={false}>Users</Link>
                <Link href="/dbtest" className="text-gray-600 hover:text-blue-600 transition-colors" prefetch={false}>Dbtest</Link>
                <Link href="/foo" className="text-gray-600 hover:text-blue-600 transition-colors" prefetch={false}>404</Link>

              </div>
            </nav>
          </div>
        </header>

        {/* Main Content */}
        <main className="max-w-4xl mx-auto px-4 py-8">
          {children}
        </main>

        {/* Footer */}
        <footer className="mt-auto bg-white border-t py-6">
          <div className="max-w-4xl mx-auto px-4 text-center text-gray-500 text-sm">
            <div>Built with Next.js and TailwindCSS</div>
            {gitInfo && (
              <div className="mt-2 text-xs">
                Commit: <span className="font-mono">{gitInfo.shortHash}</span> • {new Date(gitInfo.timestamp).toLocaleString()}
              </div>
            )}
          </div>
        </footer>
      </body>
    </html>
  );
}
